name: PR Comment Trigger

on:
  pull_request:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  run-on-pr-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Debug event
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Comment body: ${{ github.event.comment.body || 'N/A' }}"

      - name: Get PR Data
        if: github.event_name == 'issue_comment'
        id: pr_data
        uses: octokit/request-action@v2.1.0
        with:
          route: ${{ github.event.issue.pull_request.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout PR branch (from comment)
        if: github.event_name == 'issue_comment'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ fromJson(steps.pr_data.outputs.data).head.repo.full_name }}
          ref: ${{ fromJson(steps.pr_data.outputs.data).head.ref }}

      - name: Checkout PR branch (pull_request)
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v3

      - name: Run script
        run: |
          echo "Comment: ${{ github.event.comment.body || 'N/A' }}"
          python scripts/on_pr_comment.py
